# Generated by Django 5.0 on 2024-06-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EMPLOYEE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_Name', models.CharField(max_length=30)),
                ('Emp_Id', models.IntegerField()),
                ('Emp_Email_Id', models.EmailField(max_length=254)),
                ('Emp_Mobile_No', models.IntegerField()),
                ('Emp_Address', models.CharField(max_length=40)),
                ('Emp_Department', models.CharField(choices=[('Admin', 'Admin'), ('Hr', 'Hr'), ('Marketing', 'Marketing'), ('Executive', 'Executive'), ('IT', 'IT'), ('Accounting', 'Accounting'), ('Sales', 'Sales')], default='Hr', max_length=10)),
            ],
        ),
    ]
